package com.scell.converter.drawingml.main;

import com.scell.model.drawingml.main.ST_PresetColorValModel;
import org.docx4j.dml.STPresetColorVal;

public class ST_PresetColorValConverter {
  private ST_PresetColorValConverter() {
  }

  public static ST_PresetColorValModel fromDocx4j(STPresetColorVal value) {
    if (value == null) return null;
    if (value == STPresetColorVal.ALICE_BLUE) return ST_PresetColorValModel.ALICE_BLUE;
    if (value == STPresetColorVal.ANTIQUE_WHITE) return ST_PresetColorValModel.ANTIQUE_WHITE;
    if (value == STPresetColorVal.AQUA) return ST_PresetColorValModel.AQUA;
    if (value == STPresetColorVal.AQUAMARINE) return ST_PresetColorValModel.AQUAMARINE;
    if (value == STPresetColorVal.AZURE) return ST_PresetColorValModel.AZURE;
    if (value == STPresetColorVal.BEIGE) return ST_PresetColorValModel.BEIGE;
    if (value == STPresetColorVal.BISQUE) return ST_PresetColorValModel.BISQUE;
    if (value == STPresetColorVal.BLACK) return ST_PresetColorValModel.BLACK;
    if (value == STPresetColorVal.BLANCHED_ALMOND) return ST_PresetColorValModel.BLANCHED_ALMOND;
    if (value == STPresetColorVal.BLUE) return ST_PresetColorValModel.BLUE;
    if (value == STPresetColorVal.BLUE_VIOLET) return ST_PresetColorValModel.BLUE_VIOLET;
    if (value == STPresetColorVal.BROWN) return ST_PresetColorValModel.BROWN;
    if (value == STPresetColorVal.BURLY_WOOD) return ST_PresetColorValModel.BURLY_WOOD;
    if (value == STPresetColorVal.CADET_BLUE) return ST_PresetColorValModel.CADET_BLUE;
    if (value == STPresetColorVal.CHARTREUSE) return ST_PresetColorValModel.CHARTREUSE;
    if (value == STPresetColorVal.CHOCOLATE) return ST_PresetColorValModel.CHOCOLATE;
    if (value == STPresetColorVal.CORAL) return ST_PresetColorValModel.CORAL;
    if (value == STPresetColorVal.CORNFLOWER_BLUE) return ST_PresetColorValModel.CORNFLOWER_BLUE;
    if (value == STPresetColorVal.CORNSILK) return ST_PresetColorValModel.CORNSILK;
    if (value == STPresetColorVal.CRIMSON) return ST_PresetColorValModel.CRIMSON;
    if (value == STPresetColorVal.CYAN) return ST_PresetColorValModel.CYAN;
    if (value == STPresetColorVal.DK_BLUE) return ST_PresetColorValModel.DK_BLUE;
    if (value == STPresetColorVal.DK_CYAN) return ST_PresetColorValModel.DK_CYAN;
    if (value == STPresetColorVal.DK_GOLDENROD) return ST_PresetColorValModel.DK_GOLDENROD;
    if (value == STPresetColorVal.DK_GRAY) return ST_PresetColorValModel.DK_GRAY;
    if (value == STPresetColorVal.DK_GREEN) return ST_PresetColorValModel.DK_GREEN;
    if (value == STPresetColorVal.DK_KHAKI) return ST_PresetColorValModel.DK_KHAKI;
    if (value == STPresetColorVal.DK_MAGENTA) return ST_PresetColorValModel.DK_MAGENTA;
    if (value == STPresetColorVal.DK_OLIVE_GREEN) return ST_PresetColorValModel.DK_OLIVE_GREEN;
    if (value == STPresetColorVal.DK_ORANGE) return ST_PresetColorValModel.DK_ORANGE;
    if (value == STPresetColorVal.DK_ORCHID) return ST_PresetColorValModel.DK_ORCHID;
    if (value == STPresetColorVal.DK_RED) return ST_PresetColorValModel.DK_RED;
    if (value == STPresetColorVal.DK_SALMON) return ST_PresetColorValModel.DK_SALMON;
    if (value == STPresetColorVal.DK_SEA_GREEN) return ST_PresetColorValModel.DK_SEA_GREEN;
    if (value == STPresetColorVal.DK_SLATE_BLUE) return ST_PresetColorValModel.DK_SLATE_BLUE;
    if (value == STPresetColorVal.DK_SLATE_GRAY) return ST_PresetColorValModel.DK_SLATE_GRAY;
    if (value == STPresetColorVal.DK_TURQUOISE) return ST_PresetColorValModel.DK_TURQUOISE;
    if (value == STPresetColorVal.DK_VIOLET) return ST_PresetColorValModel.DK_VIOLET;
    if (value == STPresetColorVal.DEEP_PINK) return ST_PresetColorValModel.DEEP_PINK;
    if (value == STPresetColorVal.DEEP_SKY_BLUE) return ST_PresetColorValModel.DEEP_SKY_BLUE;
    if (value == STPresetColorVal.DIM_GRAY) return ST_PresetColorValModel.DIM_GRAY;
    if (value == STPresetColorVal.DODGER_BLUE) return ST_PresetColorValModel.DODGER_BLUE;
    if (value == STPresetColorVal.FIREBRICK) return ST_PresetColorValModel.FIREBRICK;
    if (value == STPresetColorVal.FLORAL_WHITE) return ST_PresetColorValModel.FLORAL_WHITE;
    if (value == STPresetColorVal.FOREST_GREEN) return ST_PresetColorValModel.FOREST_GREEN;
    if (value == STPresetColorVal.FUCHSIA) return ST_PresetColorValModel.FUCHSIA;
    if (value == STPresetColorVal.GAINSBORO) return ST_PresetColorValModel.GAINSBORO;
    if (value == STPresetColorVal.GHOST_WHITE) return ST_PresetColorValModel.GHOST_WHITE;
    if (value == STPresetColorVal.GOLD) return ST_PresetColorValModel.GOLD;
    if (value == STPresetColorVal.GOLDENROD) return ST_PresetColorValModel.GOLDENROD;
    if (value == STPresetColorVal.GRAY) return ST_PresetColorValModel.GRAY;
    if (value == STPresetColorVal.GREEN) return ST_PresetColorValModel.GREEN;
    if (value == STPresetColorVal.GREEN_YELLOW) return ST_PresetColorValModel.GREEN_YELLOW;
    if (value == STPresetColorVal.HONEYDEW) return ST_PresetColorValModel.HONEYDEW;
    if (value == STPresetColorVal.HOT_PINK) return ST_PresetColorValModel.HOT_PINK;
    if (value == STPresetColorVal.INDIAN_RED) return ST_PresetColorValModel.INDIAN_RED;
    if (value == STPresetColorVal.INDIGO) return ST_PresetColorValModel.INDIGO;
    if (value == STPresetColorVal.IVORY) return ST_PresetColorValModel.IVORY;
    if (value == STPresetColorVal.KHAKI) return ST_PresetColorValModel.KHAKI;
    if (value == STPresetColorVal.LAVENDER) return ST_PresetColorValModel.LAVENDER;
    if (value == STPresetColorVal.LAVENDER_BLUSH) return ST_PresetColorValModel.LAVENDER_BLUSH;
    if (value == STPresetColorVal.LAWN_GREEN) return ST_PresetColorValModel.LAWN_GREEN;
    if (value == STPresetColorVal.LEMON_CHIFFON) return ST_PresetColorValModel.LEMON_CHIFFON;
    if (value == STPresetColorVal.LT_BLUE) return ST_PresetColorValModel.LT_BLUE;
    if (value == STPresetColorVal.LT_CORAL) return ST_PresetColorValModel.LT_CORAL;
    if (value == STPresetColorVal.LT_CYAN) return ST_PresetColorValModel.LT_CYAN;
    if (value == STPresetColorVal.LT_GOLDENROD_YELLOW) return ST_PresetColorValModel.LT_GOLDENROD_YELLOW;
    if (value == STPresetColorVal.LT_GRAY) return ST_PresetColorValModel.LT_GRAY;
    if (value == STPresetColorVal.LT_GREEN) return ST_PresetColorValModel.LT_GREEN;
    if (value == STPresetColorVal.LT_PINK) return ST_PresetColorValModel.LT_PINK;
    if (value == STPresetColorVal.LT_SALMON) return ST_PresetColorValModel.LT_SALMON;
    if (value == STPresetColorVal.LT_SEA_GREEN) return ST_PresetColorValModel.LT_SEA_GREEN;
    if (value == STPresetColorVal.LT_SKY_BLUE) return ST_PresetColorValModel.LT_SKY_BLUE;
    if (value == STPresetColorVal.LT_SLATE_GRAY) return ST_PresetColorValModel.LT_SLATE_GRAY;
    if (value == STPresetColorVal.LT_STEEL_BLUE) return ST_PresetColorValModel.LT_STEEL_BLUE;
    if (value == STPresetColorVal.LT_YELLOW) return ST_PresetColorValModel.LT_YELLOW;
    if (value == STPresetColorVal.LIME) return ST_PresetColorValModel.LIME;
    if (value == STPresetColorVal.LIME_GREEN) return ST_PresetColorValModel.LIME_GREEN;
    if (value == STPresetColorVal.LINEN) return ST_PresetColorValModel.LINEN;
    if (value == STPresetColorVal.MAGENTA) return ST_PresetColorValModel.MAGENTA;
    if (value == STPresetColorVal.MAROON) return ST_PresetColorValModel.MAROON;
    if (value == STPresetColorVal.MED_AQUAMARINE) return ST_PresetColorValModel.MED_AQUAMARINE;
    if (value == STPresetColorVal.MED_BLUE) return ST_PresetColorValModel.MED_BLUE;
    if (value == STPresetColorVal.MED_ORCHID) return ST_PresetColorValModel.MED_ORCHID;
    if (value == STPresetColorVal.MED_PURPLE) return ST_PresetColorValModel.MED_PURPLE;
    if (value == STPresetColorVal.MED_SEA_GREEN) return ST_PresetColorValModel.MED_SEA_GREEN;
    if (value == STPresetColorVal.MED_SLATE_BLUE) return ST_PresetColorValModel.MED_SLATE_BLUE;
    if (value == STPresetColorVal.MED_SPRING_GREEN) return ST_PresetColorValModel.MED_SPRING_GREEN;
    if (value == STPresetColorVal.MED_TURQUOISE) return ST_PresetColorValModel.MED_TURQUOISE;
    if (value == STPresetColorVal.MED_VIOLET_RED) return ST_PresetColorValModel.MED_VIOLET_RED;
    if (value == STPresetColorVal.MIDNIGHT_BLUE) return ST_PresetColorValModel.MIDNIGHT_BLUE;
    if (value == STPresetColorVal.MINT_CREAM) return ST_PresetColorValModel.MINT_CREAM;
    if (value == STPresetColorVal.MISTY_ROSE) return ST_PresetColorValModel.MISTY_ROSE;
    if (value == STPresetColorVal.MOCCASIN) return ST_PresetColorValModel.MOCCASIN;
    if (value == STPresetColorVal.NAVAJO_WHITE) return ST_PresetColorValModel.NAVAJO_WHITE;
    if (value == STPresetColorVal.NAVY) return ST_PresetColorValModel.NAVY;
    if (value == STPresetColorVal.OLD_LACE) return ST_PresetColorValModel.OLD_LACE;
    if (value == STPresetColorVal.OLIVE) return ST_PresetColorValModel.OLIVE;
    if (value == STPresetColorVal.OLIVE_DRAB) return ST_PresetColorValModel.OLIVE_DRAB;
    if (value == STPresetColorVal.ORANGE) return ST_PresetColorValModel.ORANGE;
    if (value == STPresetColorVal.ORANGE_RED) return ST_PresetColorValModel.ORANGE_RED;
    if (value == STPresetColorVal.ORCHID) return ST_PresetColorValModel.ORCHID;
    if (value == STPresetColorVal.PALE_GOLDENROD) return ST_PresetColorValModel.PALE_GOLDENROD;
    if (value == STPresetColorVal.PALE_GREEN) return ST_PresetColorValModel.PALE_GREEN;
    if (value == STPresetColorVal.PALE_TURQUOISE) return ST_PresetColorValModel.PALE_TURQUOISE;
    if (value == STPresetColorVal.PALE_VIOLET_RED) return ST_PresetColorValModel.PALE_VIOLET_RED;
    if (value == STPresetColorVal.PAPAYA_WHIP) return ST_PresetColorValModel.PAPAYA_WHIP;
    if (value == STPresetColorVal.PEACH_PUFF) return ST_PresetColorValModel.PEACH_PUFF;
    if (value == STPresetColorVal.PERU) return ST_PresetColorValModel.PERU;
    if (value == STPresetColorVal.PINK) return ST_PresetColorValModel.PINK;
    if (value == STPresetColorVal.PLUM) return ST_PresetColorValModel.PLUM;
    if (value == STPresetColorVal.POWDER_BLUE) return ST_PresetColorValModel.POWDER_BLUE;
    if (value == STPresetColorVal.PURPLE) return ST_PresetColorValModel.PURPLE;
    if (value == STPresetColorVal.RED) return ST_PresetColorValModel.RED;
    if (value == STPresetColorVal.ROSY_BROWN) return ST_PresetColorValModel.ROSY_BROWN;
    if (value == STPresetColorVal.ROYAL_BLUE) return ST_PresetColorValModel.ROYAL_BLUE;
    if (value == STPresetColorVal.SADDLE_BROWN) return ST_PresetColorValModel.SADDLE_BROWN;
    if (value == STPresetColorVal.SALMON) return ST_PresetColorValModel.SALMON;
    if (value == STPresetColorVal.SANDY_BROWN) return ST_PresetColorValModel.SANDY_BROWN;
    if (value == STPresetColorVal.SEA_GREEN) return ST_PresetColorValModel.SEA_GREEN;
    if (value == STPresetColorVal.SEA_SHELL) return ST_PresetColorValModel.SEA_SHELL;
    if (value == STPresetColorVal.SIENNA) return ST_PresetColorValModel.SIENNA;
    if (value == STPresetColorVal.SILVER) return ST_PresetColorValModel.SILVER;
    if (value == STPresetColorVal.SKY_BLUE) return ST_PresetColorValModel.SKY_BLUE;
    if (value == STPresetColorVal.SLATE_BLUE) return ST_PresetColorValModel.SLATE_BLUE;
    if (value == STPresetColorVal.SLATE_GRAY) return ST_PresetColorValModel.SLATE_GRAY;
    if (value == STPresetColorVal.SNOW) return ST_PresetColorValModel.SNOW;
    if (value == STPresetColorVal.SPRING_GREEN) return ST_PresetColorValModel.SPRING_GREEN;
    if (value == STPresetColorVal.STEEL_BLUE) return ST_PresetColorValModel.STEEL_BLUE;
    if (value == STPresetColorVal.TAN) return ST_PresetColorValModel.TAN;
    if (value == STPresetColorVal.TEAL) return ST_PresetColorValModel.TEAL;
    if (value == STPresetColorVal.THISTLE) return ST_PresetColorValModel.THISTLE;
    if (value == STPresetColorVal.TOMATO) return ST_PresetColorValModel.TOMATO;
    if (value == STPresetColorVal.TURQUOISE) return ST_PresetColorValModel.TURQUOISE;
    if (value == STPresetColorVal.VIOLET) return ST_PresetColorValModel.VIOLET;
    if (value == STPresetColorVal.WHEAT) return ST_PresetColorValModel.WHEAT;
    if (value == STPresetColorVal.WHITE) return ST_PresetColorValModel.WHITE;
    if (value == STPresetColorVal.WHITE_SMOKE) return ST_PresetColorValModel.WHITE_SMOKE;
    if (value == STPresetColorVal.YELLOW) return ST_PresetColorValModel.YELLOW;
    if (value == STPresetColorVal.YELLOW_GREEN) return ST_PresetColorValModel.YELLOW_GREEN;
    return null;
  }

  public static STPresetColorVal toDocx4j(ST_PresetColorValModel value) {
    return null;
  }
}
