
package test.ooxml.drawingml.diagram;


public enum ST_ParameterIdModel {

    HORZ_ALIGN,
    VERT_ALIGN,
    CH_DIR,
    CH_ALIGN,
    SEC_CH_ALIGN,
    LIN_DIR,
    SEC_LIN_DIR,
    ST_ELEM,
    BEND_PT,
    CONN_ROUT,
    BEG_STY,
    END_STY,
    DIM,
    ROT_PATH,
    CTR_SHP_MAP,
    NODE_HORZ_ALIGN,
    NODE_VERT_ALIGN,
    FALLBACK,
    TX_DIR,
    PYRA_ACCT_POS,
    PYRA_ACCT_TX_MAR,
    TX_BL_DIR,
    TX_ANCHOR_HORZ,
    TX_ANCHOR_VERT,
    TX_ANCHOR_HORZ_CH,
    TX_ANCHOR_VERT_CH,
    PAR_TX_L_T_R_ALIGN,
    PAR_TX_R_T_L_ALIGN,
    SHP_TX_L_T_R_ALIGN_CH,
    SHP_TX_R_T_L_ALIGN_CH,
    AUTO_TX_ROT,
    GR_DIR,
    FLOW_DIR,
    CONT_DIR,
    BKPT,
    OFF,
    HIER_ALIGN,
    BK_PT_FIXED_VAL,
    ST_BULLET_LVL,
    ST_ANG,
    SPAN_ANG,
    AR,
    LN_SP_PAR,
    LN_SP_AF_PAR_P,
    LN_SP_CH,
    LN_SP_AF_CH_P,
    RT_SHORT_DIST,
    ALIGN_TX,
    PYRA_LVL_NODE,
    PYRA_ACCT_BKGD_NODE,
    PYRA_ACCT_TX_NODE,
    SRC_NODE,
    DST_NODE,
    BEG_PTS,
    END_PTS,
}