
package test.ooxml.drawingml.main;


public enum ST_LightRigTypeModel {

    LEGACY_FLAT1,
    LEGACY_FLAT2,
    LEGACY_FLAT3,
    LEGACY_FLAT4,
    LEGACY_NORMAL1,
    LEGACY_NORMAL2,
    LEGACY_NORMAL3,
    LEGACY_NORMAL4,
    LEGACY_HARSH1,
    LEGACY_HARSH2,
    LEGACY_HARSH3,
    LEGACY_HARSH4,
    THREE_PT,
    BALANCED,
    SOFT,
    HARSH,
    FLOOD,
    CONTRASTING,
    MORNING,
    SUNRISE,
    SUNSET,
    CHILLY,
    FREEZING,
    FLAT,
    TWO_PT,
    GLOW,
    BRIGHT_ROOM,
}