package com.scell.model.drawingml.main;

public enum PresetCameraTypeValueModel {
  LEGACY_OBLIQUE_TOP_LEFT,

  LEGACY_OBLIQUE_TOP,

  LEGACY_OBLIQUE_TOP_RIGHT,

  LEGACY_OBLIQUE_LEFT,

  LEGACY_OBLIQUE_FRONT,

  LEGACY_OBLIQUE_RIGHT,

  LEGACY_OBLIQUE_BOTTOM_LEFT,

  LEGACY_OBLIQUE_BOTTOM,

  LEGACY_OBLIQUE_BOTTOM_RIGHT,

  LEGACY_PERSPECTIVE_TOP_LEFT,

  LEGACY_PERSPECTIVE_TOP,

  LEGACY_PERSPECTIVE_TOP_RIGHT,

  LEGACY_PERSPECTIVE_LEFT,

  LEGACY_PERSPECTIVE_FRONT,

  LEGACY_PERSPECTIVE_RIGHT,

  LEGACY_PERSPECTIVE_BOTTOM_LEFT,

  LEGACY_PERSPECTIVE_BOTTOM,

  LEGACY_PERSPECTIVE_BOTTOM_RIGHT,

  ORTHOGRAPHIC_FRONT,

  ISOMETRIC_TOP_UP,

  ISOMETRIC_TOP_DOWN,

  ISOMETRIC_BOTTOM_UP,

  ISOMETRIC_BOTTOM_DOWN,

  ISOMETRIC_LEFT_UP,

  ISOMETRIC_LEFT_DOWN,

  ISOMETRIC_RIGHT_UP,

  ISOMETRIC_RIGHT_DOWN,

  ISOMETRIC_OFF_AXIS_1_LEFT,

  ISOMETRIC_OFF_AXIS_1_RIGHT,

  ISOMETRIC_OFF_AXIS_1_TOP,

  ISOMETRIC_OFF_AXIS_2_LEFT,

  ISOMETRIC_OFF_AXIS_2_RIGHT,

  ISOMETRIC_OFF_AXIS_2_TOP,

  ISOMETRIC_OFF_AXIS_3_LEFT,

  ISOMETRIC_OFF_AXIS_3_RIGHT,

  ISOMETRIC_OFF_AXIS_3_BOTTOM,

  ISOMETRIC_OFF_AXIS_4_LEFT,

  ISOMETRIC_OFF_AXIS_4_RIGHT,

  ISOMETRIC_OFF_AXIS_4_BOTTOM,

  OBLIQUE_TOP_LEFT,

  OBLIQUE_TOP,

  OBLIQUE_TOP_RIGHT,

  OBLIQUE_LEFT,

  OBLIQUE_RIGHT,

  OBLIQUE_BOTTOM_LEFT,

  OBLIQUE_BOTTOM,

  OBLIQUE_BOTTOM_RIGHT,

  PERSPECTIVE_FRONT,

  PERSPECTIVE_LEFT,

  PERSPECTIVE_RIGHT,

  PERSPECTIVE_ABOVE,

  PERSPECTIVE_BELOW,

  PERSPECTIVE_ABOVE_LEFT_FACING,

  PERSPECTIVE_ABOVE_RIGHT_FACING,

  PERSPECTIVE_CONTRASTING_LEFT_FACING,

  PERSPECTIVE_CONTRASTING_RIGHT_FACING,

  PERSPECTIVE_HEROIC_LEFT_FACING,

  PERSPECTIVE_HEROIC_RIGHT_FACING,

  PERSPECTIVE_HEROIC_EXTREME_LEFT_FACING,

  PERSPECTIVE_HEROIC_EXTREME_RIGHT_FACING,

  PERSPECTIVE_RELAXED,

  PERSPECTIVE_RELAXED_MODERATELY
}
